### ISSUE TITLE
Roadmap before Full Release

### ISSUE THREAD

**Issue by ValiantWind** [ValiantWind/cloudblox#1]
Features to be added before the API Wrapper is ready for Productive Use

- [ ] Support for each Roblox Web API, including but not limited to the following:
  - [x] [Account Information API](https://accountinformation.roblox.com/docs)
  - [x] [Account Settings API](https://accountsettings.roblox.com/docs)
  - [ ] [Authentication API](https://auth.roblox.com/docs#!/v1)
  - [x] [Avatar API](https://avatar.roblox.com/docs/index.html)
  - [x] [Badges API](https://badges.roblox.com/docs/index.html)
  - [x] [Catalog API](https://catalog.roblox.com/docs#!/v1)
  - [x] [Chat API](https://chat.roblox.com/docs/index.html)
  - [x] [Contacts API](https://contacts.roblox.com/docs/index.html)
  - [x] [Develop API](https://develop.roblox.com/docs)
  - [ ] [Economy API](https://economy.roblox.com/docs#!/v1)
  - [x] [Engagement Payouts API](https://engagementpayouts.roblox.com/docs)
  - [x] [Followings API](https://followings.roblox.com/docs/index.html)
  - [x] [Friends API](https://friends.roblox.com/docs/index.html)
  - [x] [Games API](https://games.roblox.com/docs/index.html)
  - [x] [Groups API](https://groups.roblox.com/docs/index.html)
  - [x] [Inventory API](https://inventory.roblox.com/docs)
  - [x] [Presence API](https://presence.roblox.com/docs/index.html)
  - [ ] [Private Messages API](https://privatemessages.roblox.com/docs)
  - [ ] [Publish API](https://publish.roblox.com/docs)
  - [ ] [Thumbnails API](https://thumbnails.roblox.com/docs/index.html)
  - [ ] [Trades API](https://trades.roblox.com/docs)
  - [ ] [Translations API](https://translations.roblox.com/docs)
  - [ ] [Two Step Verification API](https://twostepverification.roblox.com/docs/index.html)
  - [x] [Users API](https://users.roblox.com/docs/index.html)
  - [ ] Other Undocumented Endpoints

- [ ] Typing declarations for everything
- [x] Cookie Authentication Support
- [x] API Authentication Support So the Open Cloud Methods actually work
